#define M_PI 3.14159265358979

#define SCREEN_SIZE_WIDTH 840
#define SCREEN_SIZE_HEIGHT 630

#define FIELD_OFFSET_X 24
#define FIELD_OFFSET_Y 24
#define FIELD_SIZE_WIDTH  516
#define FIELD_SIZE_HEIGHT 582
#define SCOREBOARD_OFFSET_X 540
#define SCOREBOARD_OFFSET_Y 24


#define EN_ORDER_MAX 200
#define EN_KIND_MAX 22
#define ENEMY_MAX 50

#define ENEMY_WIDTH 32
#define ENEMY_HEIGHT 32

#define EN_LAZER_MAX 200
#define EN_LAZER_DIV_MAX 64

#define EN_SPELL_WIDTH 12
#define EN_SPELL_HEIGHT 12

#define EN_BULLET_MAX 1000
#define EN_BARRAGE_MAX 50

#define BO_BARRAGE_MAX 6

#define PLAYER_WIDTH 32
#define PLAYER_HEIGHT 32

#define PL_SUBWEAPON_MAX 6
#define PL_SUBWEAPON_WIDTH 16
#define PL_SUBWEAPON_HEIGHT 16

#define PL_BULLET_MAX 200
#define PL_SHOT_BET_TIME 6

#define PL_BOMB_WIDTH 200
#define PL_BOMB_HEIGHT 200

#define PL_STATUS_WIDTH 32
#define PL_STATUS_HEIGHT 32

#define EXPLODE_WIDTH 48
#define EXPLODE_HEIGHT 48

#define ITEM_MAX 90
#define ITEM_S_WIDTH 8
#define ITEM_S_HEIGHT 8
#define ITEM_L_WIDTH 12
#define ITEM_L_HEIGHT 12